### ISSUE TITLE
add to intake?

### ISSUE THREAD

**Issue by martindurant** [anaconda/intake-google-analytics#3]
Should this repo be listed in https://intake.readthedocs.io/en/latest/plugin-directory.html , and/or would you like to move it to the intake org to get more visibility?

**Comment by AlbertDeFusco** [comment]
Sure, I'm happy to move this one to the Intake org. I'll setup a PR for the directory.

**Comment by martindurant** [comment]
To move, I think either I would need to be an admin here, or you would need to be at least "maintainer" in the intake org. I am happy with both.

**Comment by AlbertDeFusco** [comment]
Sure, I'll add you as an admin here an I'm happy to assume maintainer status on Intake

**Comment by martindurant** [comment]
Done.
